### PR TITLE
CNI pages only

### PR DESCRIPTION
**Pull request by evilnick**
I have stripped out the other config pages and the reference section as just these pages on thier own can work and it will make a more landable group of pages for ubuntu.com

### CODE REVIEW

**Comment by evilnick** [comment]
@Cynerva , as you can see, the calico page is currently little more than a stub, but if you check the corresponding flannel page you can see more of the structure. I want to present all the config options in a table (I think, complete on the Calico page) and then underneath that include any sections with notable/useful examples

**Comment by Cynerva** [comment]
I like the overall structure of this. Cheers.

The placement of the charm config tables here is interesting. When I think of other software documentation I've seen, I usually see comprehensive lists and tables and such (e.g. command line options) buried away in a Reference section at the end of the documentation. Some recent examples: [Kubernetes](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/), [Calico](https://docs.projectcalico.org/v3.6/reference/node/configuration). I initially imagined we'd do the same with charm config options.

Maybe placing them inline with the main documentation makes more sense, though. It's hard to think of any concrete reasons why they -wouldn't- belong there.

Could they be disruptive to the usual flow of the documentation? Normally the docs start with concepts, and then tell you how to apply them. The config tables go the other way: they tell you what can be applied, and then (minimally) explain the concept behind them.

In any case, I don't see any concrete problems here, but I'm curious to hear what you think.

**Comment by evilnick** [comment]
Thanks. My decision to put the options further up is based on two or three things really.

 1, in some ways it can serve as a sort of table of contents of what is actually possible. I agree that in most instructions the implementation would be hidden away, but I actually think that, similar to actions, the config is more or less the essence of what the charm does, or at least the knobs to turn and make it do those things.

2. I imagine for most people, the entire reason for visiting this page more than once is actually for that table, so having it more visible is an advantage.

3. If they were *big* tables with lots of options and explanations, I would be more inclined to think it could be overwhelming, but usually we only have three or four things. It doesn't even need to be a table, that just makes it neater - you could just as easily have a header and section about each, but I think this makes it more compact and useful. Will be interesting to see if we get any feedback from users. Personally I find it annoying going to a page to read about X, then finding out the info I need about X is hidden in some appendix.

**Comment by evilnick** [comment]
I'm going to merge this into a new branch to make it easier to add the BGP stuff

**Pull request merged**
