### PR TITLE
Release notes for 1.23

### PR DESCRIPTION
**Pull request by Cynerva**

### CODE REVIEW

**Comment by Cynerva** [comment]
I've pulled in the content from https://github.com/charmed-kubernetes/kubernetes-docs/pull/617.

**Comment by Cynerva** [comment]
The release is still under testing by SQA. Will update the release date when they are done.

**Comment by evilnick** [comment]
cool, thanks for this. Barring any issues, is 862 likely to be the final revision? I can prep some docs based on that if so

**Comment by Cynerva** [comment]
@evilnick Yep, we just got the all clear from SQA. We'll be releasing today with 862.

I've got one last thing I'm gonna try to add a note for: https://bugs.launchpad.net/charm-etcd/+bug/1913327

**Comment by Cynerva** [comment]
Done with the release to stable. Let me know if there's anything you'd like me to change here, otherwise I will leave it to you and get out of the way. :)

**Pull request merged**
