### PR TITLE
update logging docs to align with ncsc

### PR DESCRIPTION
**Pull request by kwmonroe**
Update the deployment examples.  Call out audit logging and where to find more info.  Fix upstream links.

### CODE REVIEW

**Review by evilnick — COMMENTED** [review]
wasn't sure if you are still making changes to this. Looks fine so far

**Comment by kwmonroe** [comment]
> wasn't sure if you are still making changes to this. Looks fine so far

thanks for the early review!  i'm miffed by both Logging and Audit Logging in our Operations section.  i want to try combining those or perhaps tucking the audit bits under Security.  i'll have a look through the preview both ways and see what sticks.

**Comment by evilnick** [comment]
@kwmonroe I think that was a decision taken in the past by powers greater than our own. but he is playing golf somewhere else now so we can do what we want.

I do think audit logging probably belongs in security. Bear in mind all these things will likely move around under diataxis anyway

**Comment by kwmonroe** [comment]
Yeah, i don't like the combined look either :)  at least the content is right with this; i'll switch it to 'ready' and mess with layout later.

**Review by evilnick — APPROVED** [review]

**Pull request merged**
