### PR TITLE
Quickstart 20.04 update

### PR DESCRIPTION
**Pull request by alxchalkias**

### CODE REVIEW

**Comment by tvansteenburgh** [comment]
LGTM, but let's hold off on merging until 20.04 is released, or until we hear from @alxchalkias that we should merge before then.

**Comment by evilnick** [comment]
@tvansteenburgh agree. I also think we will need to add this to the website as well as the docs

**Comment by alxchalkias** [comment]
@evilnick I have checked all K8s related pages for LTS mentions and there were none. What's the idea about adding "20.04 LTS" to the website?

**Comment by evilnick** [comment]
@alxchalkias Yes, what I really meant was we should check and update the 'other' install page on ubuntu.com (https://ubuntu.com/kubernetes/install), but you are right, it doesn't even mention Ubuntu versions one there

**Pull request merged**
