### PR TITLE
Cni overlays

### PR DESCRIPTION
**Pull request by evilnick**
Created overlay files for deployment with specific CNI options.

### CODE REVIEW

**Comment by evilnick** [comment]
@Cynerva I'm a little unsure of the canal one. The published bundle uses Docker instead of containerd - I didn't know if there was a particular reason for that?

**Comment by Cynerva** [comment]
Canal with containerd should be OK now.

The canal bundle uses docker because we didn't quite have Canal + containerd support ([PR](https://github.com/charmed-kubernetes/layer-canal/pull/34)) merged when we started the C~D~K 1.15 release process. It looks like the final release did end up including that, though -- I see containerd support in the canal charm in stable.

I'll make sure that bundle gets updated to use containerd in the next release.

**Comment by Cynerva** [comment]
The canal and tigera-secure-ee fragments are using the latest charm and resource revisions from edge, not stable. We want stable revisions right?

**Comment by evilnick** [comment]
Ah, yes. I will adjust the versions. Thanks

**Comment by evilnick** [comment]
@Cynerva okay, I have made these all non-specific now

**Comment by Cynerva** [comment]
:+1: LGTM

**Comment by Cynerva** [comment]
Follow-up on getting the canal bundle updated: https://github.com/charmed-kubernetes/jenkins/pull/453

**Comment by evilnick** [comment]
ta

**Pull request merged**
