### PR TITLE
Add missing relations on snapshot restore

### LINKED ISSUE #372: Missing relations on snapshot restore
The steps currently described to restore an etcd snapshot deploy a new easyrsa application, but those steps miss relating it to kubernetes-worker, kubernetes-master and kubeapi-load-balancer applications.

### PR DESCRIPTION
**Pull request by tpsilva**
The steps currently described to restore an etcd snapshot deploy
a new easyrsa application, but those steps miss relating it to
kubernetes-worker, kubernetes-master and kubeapi-load-balancer
applications. This patch includes those relations in the
documentation.

Fixes #372

### CODE REVIEW

**Comment by evilnick** [comment]
Hi, many thanks for contributing this. Some of these connections are in the docs further down, after the snapshot has been restored, which is the preferred sequence. However, it seems that not all the required relations are there.
I will modify your PR to put these in the right place if that's okay with you

**Comment by tpsilva** [comment]
That's ok! Thanks!

**Comment by tpsilva** [comment]
@evilnick Is it correct to remove the relation between new-etcd and kubernetes-master? Is that not needed?

**Comment by evilnick** [comment]
@tpsilva yes it is needed - sorry, I wasn't really finished with this yet

**Comment by evilnick** [comment]
@tpsilva Sorry about the confusion, I should have edited this properly instead of on github. Not so easy to 'save as you go'

The only thing I now wonder is if we should add some commands to clean up - e.g. we don't mention any existing easyrsa/etcd. What do you think?

**Comment by tpsilva** [comment]
@evilnick I agree that this would be useful. Currently that is implicit in the documentation, but it would be nice to mention that the older units should be removed.

**Comment by evilnick** [comment]
In the interests of getting this fixed up I will merge this now and I generated a new issue to add some cleanup steps (would rather take the time to run through it and test).

Thanks for your help!

**Pull request merged**
