### PR TITLE
Add Kube-OVN documentation

### PR DESCRIPTION
**Pull request by Cynerva**
I'm still working on this, but here is my progress so far.

### CODE REVIEW

**Comment by Cynerva** [comment]
This is ready for review :)

**Comment by Cynerva** [comment]
This depends on https://github.com/charmed-kubernetes/bundle/pull/856 for kube-ovn-overlay.yaml

**Review by kwmonroe — APPROVED** [review]
nice.  :100: on the shoutouts for o11y/registry integrations.

**Review by evilnick — APPROVED** [review]
:cake:

**Pull request merged**
